version: "3.9"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./teamc-app:/app
      - node_modules_volume:/app/node_modules
    #"react-app"の部分がプロジェクト名になる
    command: sh -c "yarn start" 
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  node_modules_volume:
